/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as CandidatoRouteImport } from './routes/candidato'
import { Route as EmailVerificationRouteImport } from './routes/email-verification'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CandidatoPerfilRouteImport } from './routes/candidato.perfil'
import { Route as UsersRegisterRouteImport } from './routes/users/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoRoute = CandidatoRouteImport.update({
  id: '/candidato',
  path: '/candidato',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerificationRoute = EmailVerificationRouteImport.update({
  id: '/email-verification',
  path: '/email-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatoPerfilRoute = CandidatoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => CandidatoRoute,
} as any)
const UsersRegisterRoute = UsersRegisterRouteImport.update({
  id: '/users/register',
  path: '/users/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/email-verification': typeof EmailVerificationRoute
  '/empresa': typeof EmpresaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/candidato/perfil': typeof CandidatoPerfilRoute
  '/users/register': typeof UsersRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/email-verification': typeof EmailVerificationRoute
  '/empresa': typeof EmpresaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/candidato/perfil': typeof CandidatoPerfilRoute
  '/users/register': typeof UsersRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrador': typeof AdministradorRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/candidato': typeof CandidatoRouteWithChildren
  '/email-verification': typeof EmailVerificationRoute
  '/empresa': typeof EmpresaRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/candidato/perfil': typeof CandidatoPerfilRoute
  '/users/register': typeof UsersRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrador'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/candidato'
    | '/email-verification'
    | '/empresa'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/candidato/perfil'
    | '/users/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrador'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/candidato'
    | '/email-verification'
    | '/empresa'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/candidato/perfil'
    | '/users/register'
  id:
    | '__root__'
    | '/'
    | '/administrador'
    | '/cadastro'
    | '/cadastro-empresa'
    | '/candidato'
    | '/email-verification'
    | '/empresa'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/candidato/perfil'
    | '/users/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministradorRoute: typeof AdministradorRoute
  CadastroRoute: typeof CadastroRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  CandidatoRoute: typeof CandidatoRouteWithChildren
  EmailVerificationRoute: typeof EmailVerificationRoute
  EmpresaRoute: typeof EmpresaRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UsersRegisterRoute: typeof UsersRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato': {
      id: '/candidato'
      path: '/candidato'
      fullPath: '/candidato'
      preLoaderRoute: typeof CandidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-verification': {
      id: '/email-verification'
      path: '/email-verification'
      fullPath: '/email-verification'
      preLoaderRoute: typeof EmailVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidato/perfil': {
      id: '/candidato/perfil'
      path: '/perfil'
      fullPath: '/candidato/perfil'
      preLoaderRoute: typeof CandidatoPerfilRouteImport
      parentRoute: typeof CandidatoRoute
    }
    '/users/register': {
      id: '/users/register'
      path: '/users/register'
      fullPath: '/users/register'
      preLoaderRoute: typeof UsersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CandidatoRouteChildren {
  CandidatoPerfilRoute: typeof CandidatoPerfilRoute
}

const CandidatoRouteChildren: CandidatoRouteChildren = {
  CandidatoPerfilRoute: CandidatoPerfilRoute,
}

const CandidatoRouteWithChildren = CandidatoRoute._addFileChildren(
  CandidatoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministradorRoute: AdministradorRoute,
  CadastroRoute: CadastroRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  CandidatoRoute: CandidatoRouteWithChildren,
  EmailVerificationRoute: EmailVerificationRoute,
  EmpresaRoute: EmpresaRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UsersRegisterRoute: UsersRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
